// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// MockNotification is an autogenerated mock type for the Notification type
type MockNotification struct {
	mock.Mock
}

type MockNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotification) EXPECT() *MockNotification_Expecter {
	return &MockNotification_Expecter{mock: &_m.Mock}
}

// NewMockNotification creates a new instance of MockNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotification {
	mock := &MockNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
