// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock

import (
	context "context"

	dispatcher "github.com/adnvilla/dispatcher-go"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationHandler is an autogenerated mock type for the NotificationHandler type
type MockNotificationHandler[TNotification dispatcher.Notification] struct {
	mock.Mock
}

type MockNotificationHandler_Expecter[TNotification dispatcher.Notification] struct {
	mock *mock.Mock
}

func (_m *MockNotificationHandler[TNotification]) EXPECT() *MockNotificationHandler_Expecter[TNotification] {
	return &MockNotificationHandler_Expecter[TNotification]{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, notification
func (_m *MockNotificationHandler[TNotification]) Handle(ctx context.Context, notification TNotification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, TNotification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockNotificationHandler_Handle_Call[TNotification dispatcher.Notification] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - notification TNotification
func (_e *MockNotificationHandler_Expecter[TNotification]) Handle(ctx interface{}, notification interface{}) *MockNotificationHandler_Handle_Call[TNotification] {
	return &MockNotificationHandler_Handle_Call[TNotification]{Call: _e.mock.On("Handle", ctx, notification)}
}

func (_c *MockNotificationHandler_Handle_Call[TNotification]) Run(run func(ctx context.Context, notification TNotification)) *MockNotificationHandler_Handle_Call[TNotification] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(TNotification))
	})
	return _c
}

func (_c *MockNotificationHandler_Handle_Call[TNotification]) Return(_a0 error) *MockNotificationHandler_Handle_Call[TNotification] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationHandler_Handle_Call[TNotification]) RunAndReturn(run func(context.Context, TNotification) error) *MockNotificationHandler_Handle_Call[TNotification] {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationHandler creates a new instance of MockNotificationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationHandler[TNotification dispatcher.Notification](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationHandler[TNotification] {
	mock := &MockNotificationHandler[TNotification]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
