run:
  tests: false
  go: '1.22'
issues:
  exclude-files:
    - 'wire_gen.go'
  exclude-dirs:
    - docs
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    sections:
      - standard
      - default
  depguard:
    rules:
      Master:
        files:
          - $all
          - "!$test"
        deny:
          - pkg: "github.com/satori/go.uuid"
            desc: Prefer "github.com/google/uuid"
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - depguard
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
